/**
 * Authoritative list of memory-object keys. Every key must have an ObjectDef in
 * src/objects/builders/*. `crystal` is the generic "mystery crystal" fallback.
 */
export const OBJECT_KEYS = [
  // science & tech
  'pendulum',
  'rocket',
  'atom',
  'dna',
  'heart',
  'cell',
  'magnet',
  'lightbulb',
  'battery',
  'flask',
  'telescope',
  'microscope',
  'prism',
  'lightning',
  'brain',
  'eye',
  'droplet',
  'flame',
  'spring',
  'wave',
  'planet',
  'sun',
  'moon',
  // culture, history, tools, nature
  'book',
  'scroll',
  'sword',
  'crown',
  'fort',
  'globe',
  'tree',
  'mountain',
  'key',
  'lock',
  'scales',
  'coin',
  'pyramid',
  'volcano',
  'leaf',
  'bridge',
  'clock',
  'compass',
  'lantern',
  'anvil',
  'bell',
  'gear',
  'shield',
  'flag',
  'hourglass',
  'flower',
  'ship',
  'cannon',
  'temple',
  'quill',
  'trophy',
  'candle',
  'map',
  'mortar',
  'crystal',
] as const;

export type ObjectKey = (typeof OBJECT_KEYS)[number];
export const FALLBACK_OBJECT_KEY: ObjectKey = 'crystal';
